#! /usr/bin/env python

import rospy
from hrwros_msgs.msg import BoxHeightInformation
from hrwros_msgs.srv import ConvertMetresToFeet, ConvertMetresToFeetRequest, ConvertMetresToFeetResponse

def box_height_info_callback(data):
    try:
        metres_to_feet = rospy.ServiceProxy('metres_to_feet', ConvertMetresToFeet)
        service_response = metres_to_feet(x)
        print("Measurement done")
    except rospy.ServiceException, e:
        print "Service call failed: %s"%e

if __name__ == '__main__':
    rospy.init_node('box_height_in_feet', anonymous = False)
    rospy.loginfo("Waiting for service...")
    rospy.wait_for_service('metres_to_feet')
    rospy.loginfo("Service %s is now available", 'metres_to_feet')
    rospy.Subscriber(Subscriber, string, Publisher)
    rospy.spin()
